apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-deployment-dev
  namespace: cyk-dev
spec:
  selector:
    matchLabels:
      type: front
  replicas: 1
  template:
    metadata:
      labels:
        type: front
    spec:
      containers:
      - name: container
        image: cykim43/front_jenkins:latest
        command: ["/bin/sh", "-ec", "envsubst '$BACK_SVC' < /etc/nginx/conf.d/default.conf.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"]
        envFrom:
        - configMapRef:
            name: front-cm
        ports:
        - containerPort: 80